- name : Configure Docker on EC2 Instances
  hosts : test-server
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : root

  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : root
    
  - name: Remove old container if it exists
    shell: docker rm -f insureme-app || true
  
  - name: Deploy Docker Container
    command: docker run -itd -p 8081:8081 kundanadileepm/insureme-app:latest
